name: travel_app
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flashy_tab_bar2: ^0.0.4
  flutter_native_splash: ^2.2.10+1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^3.0.1
  readmore: ^2.2.0
  tab_indicator_styler: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: false
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/flutter.png
  web: true
  android_12:
    image: assets/flutter.png
    icon_background_color: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - assets/flutter.png
    - assets/logo.png
